### ISSUE TITLE
Clients should be able to tell if data came from multicast or unicast

### ISSUE THREAD

**Issue by MaxF12** [GrumpyOldTroll/draft-jholland-quic-multicast#1]
Last sentence of section 2 reads: 

`An application using a multicast-capable QUIC implementation that receives a datagram or stream data has no knowledge at the application layer whether multicast was used or not used for that data, it will only know it has received unidirectional server-to-client application data.`

As the security and privacy guarantees for data that has been delivered over multicast are (inherently) lower than over unicast, I feel like this could cause serious issues for applications. I think that any implementation that supports multicast delivery has to at least make it clear to the application that the data has been delivered over multicast, or even better yet only allow multicast delivery if the application opted in for it.

**Comment by GrumpyOldTroll** [comment]
+1, yes thanks and good point.  I should probably add "if the receiver has opted into receiving multicast".

**Comment by GrumpyOldTroll** [comment]
Closed with https://github.com/GrumpyOldTroll/draft-jholland-quic-multicast/pull/6
