### ISSUE TITLE
Session already has a meaning in QUIC

### ISSUE THREAD

**Issue by GrumpyOldTroll** [GrumpyOldTroll/draft-jholland-quic-multicast#10]
"Session" already has a meaning in QUIC.  It appears to be implicitly imported via TLS, c.f.:
 - https://www.rfc-editor.org/rfc/rfc9000#section-14.2.1-4
 - https://www.rfc-editor.org/rfc/rfc9001.html#name-session-resumption
 - https://www.rfc-editor.org/rfc/rfc8446.html#section-2.2

I'm thinking maybe we can search & replace "session" with "channel"?

"Channel" also has a meaning in SSM (c.f. https://www.rfc-editor.org/rfc/rfc4607.html#page-4), but using it here would be complementary instead of divergent.  ("Channel" in SSM refers to a network path, and likewise if we used it instead of "Session" in the QUIC extensions it would refer to a network path and associated objects...)

**Comment by MaxF12** [comment]
I agree that channel would fit well with its meaning in SSM, only thing to keep in mind is that QUIC specifies a stream as `A unidirectional or bidirectional channel of ordered bytes within a QUIC connection.`

I think there should be no confusion there though.

**Comment by GrumpyOldTroll** [comment]
Yes, I don't think that will cause nearly as much confusion as "session".

A grep for "channel" in google's quiche suggests that it once had a meaning back when the project was spdy and there are some remnants still in the code, but these also have a much smaller footprint than "session", and I think are only in obsolete parts, c.f.:

~~~
net/third_party/quiche/src/quic/core/tls_server_handshaker.cc:  // Channel ID is not supported when TLS is used in QUIC.
~~~

**Comment by GrumpyOldTroll** [comment]
Sessions have been renamed to channels.
