### ISSUE TITLE
Client behavior when unicast connection is disrupted

### ISSUE THREAD

**Issue by MaxF12** [GrumpyOldTroll/draft-jholland-quic-multicast#12]
How would a client behave if the unicast connection is interrupted but the Multicast channels still receive data? It wouldn’t be able to check the integrity of any packets, but it isn’t exactly idling either so the idle connection timeout would not trigger I guess? Should this be clarified so that all multicast session are left and the entire connection is shutdown if there is no message over the unicast connection for longer than the idle timeout?

**Comment by GrumpyOldTroll** [comment]
Yeah, good question.  I guess maybe the client should actively ensure it still has unicast connectivity and leave sessions if it can't prove it does, on a timescale similar to max idle (or maybe another value?).

I guess if client gets no packts for some time on unicast, it should probably send a ping, and if it still has no ack after some time it should leave its sessions with a reason like "failed unicast".  But yes, there should certainly be a section detailing the behavior, good point.
