### ISSUE TITLE
move aead algorithm to CHANNEL_ANNOUNCE

### ISSUE THREAD

**Issue by GrumpyOldTroll** [GrumpyOldTroll/draft-jholland-quic-multicast#42]
Suggested change from @squarooticus :

Announce the payload AEAD algorithm in CHANNEL_ANNOUNCE and just assume it isn't going to change for the lifetime of the channel. This probably works better with existing QUIC stacks that assume only the key, rather than the alg, will change during a connection.

**Comment by MaxF12** [comment]
Would maybe also make sense for the hash algorithm?

**Comment by squarooticus** [comment]
Yes, I definitely mean both.

**Comment by MaxF12** [comment]
Closed by #55

**Comment by squarooticus** [comment]
Yes. I definitely mean both.
