### ISSUE TITLE
MC_SESSION_INTEGRITY

### ISSUE THREAD

**Issue by MaxF12** [GrumpyOldTroll/draft-jholland-quic-multicast#5]
`For type TBD-05, Length is present and is a count of packet hashes. For TBD-04, Length is not present and the packet hashes extend to the end of the packet.`

Should this read "[...] extend to the end of the session."?

**Comment by GrumpyOldTroll** [comment]
No, this should be "to the end of the QUIC packet".  Compare to the phrasing and the type selection for the datagram length field: https://www.rfc-editor.org/rfc/rfc9221.html#section-4-5.2.1

A MC_SESSION_INTEGRITY frame either needs a length (when followed by another frame) or it doesn't (when it extends to the end of the packet), and can maybe fit one extra hash.

**Comment by GrumpyOldTroll** [comment]
Yes, my intent was that a MC_SESSION_INTEGRITY frame contains in-order packets and uses the "packet number start" field as the packet number of the first hash in the frame:
https://grumpyoldtroll.github.io/draft-jholland-quic-multicast/draft-jholland-quic-multicast.html#name-mc_session_integrity

I should clean that explanation up for sure, yes.

**Comment by GrumpyOldTroll** [comment]
Closed via https://github.com/GrumpyOldTroll/draft-jholland-quic-multicast/pull/7
