### ISSUE TITLE
Add channel state diagrams

### ISSUE THREAD

**Issue by GrumpyOldTroll** [GrumpyOldTroll/draft-jholland-quic-multicast#50]
We at least need a channel state diagram for client, and probably also for server.
(like https://www.rfc-editor.org/rfc/rfc9000#fig-stream-send-states and https://www.rfc-editor.org/rfc/rfc9000#fig-stream-recv-states and https://www.ietf.org/archive/id/draft-ietf-quic-multipath-01.html#fig-path-states)

**Comment by MaxF12** [comment]
Agreed, I was thinking about states when I made the object as well. So far I have 4 (Idle, joining, joined and timed out). Do you think we need more?

**Comment by GrumpyOldTroll** [comment]
I think I was thinking different names for them in the client, but maybe :
 - unjoined
 - attempting join (joined and MC_CLIENT_CHANNEL_STATE: Joined sent, but no data received yet)
 - joined (data received and MC_CHANNEL_ACK sent)
 - held down (timer or status prevents joining--generally should go here after an error but not a clean leave)

For the server side I was thinking:
 - client unjoined
 - client pending join (sent a MC_CHANNEL_JOIN, no MC_CLIENT_CHANNEL_STATE received yet)
 - client joined (MC_CLIENT_CHANNEL_STATE with Joined received)
 - client pending leave
 - client held down (unjoined and server will not currently retry join due to prior error)

I wasn't sure whether we need a "client confirmed" state where we've seen an ack of channel data on the server, I'm ambivalent on it.

I think it might also be useful to define some hold-down conditions and timers, which I don't think we've gotten into yet.  We probably need a retry section and some general advice about how to handle error-based leave/decline events that hold down a retry for some time, maybe a growing time.
