### ISSUE TITLE
Add operational considerations section

### ISSUE THREAD

**Issue by MaxF12** [GrumpyOldTroll/draft-jholland-quic-multicast#61]
Depending on size might also be a separate ID.
- Include reference to CBACC
- Include fan out/ deployment strategies
- Graceful degradation (#44)
- Pool/ Channel management on the server side
- Reusing the same S,G for multiple channels might have implications for the rate on the network
- ...

**Comment by GrumpyOldTroll** [comment]
Reference to CBACC should also mention that popularity-based metrics within a multicast network imply that clients SHOULD NOT leave just because they are not receiving traffic, if they are otherwise willing to receive multicast and server has asked them to try (also the reason behind fixing #63).
