### ISSUE TITLE
What's a "liveness test"?

### ISSUE THREAD

**Issue by LPardue** [GrumpyOldTroll/draft-jholland-quic-multicast#91]
> If the unicast connection becomes idle and the server does not respond to a liveness test, the client MUST terminate the connection as described above.

I don't follow this. QUIC endpoints that want to avoid the connection going idle are obligated to keep to it alive. There isn't a concept of testing after the period has elapsed, that would be too late.

**Comment by MaxF12** [comment]
Probably me not being clear enough, I was trying to refer to section 10.1.1. and the mechanic described there, I will rephrase.
